.TH "libirc_doc.h" 3 "8 Sep 2004" "libirc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libirc_doc.h \- This file contains Doxygen modules. 
.SH SYNOPSIS
.br
.PP
.SH "DETAILED DESCRIPTION"
.PP 
This file contains Doxygen modules.
.PP
.PP
\fBAuthor: \fP
.in +1c
Georgy Yunaev 
.PP
\fBVersion: \fP
.in +1c
1.0 
.PP
\fBDate: \fP
.in +1c
09.2004
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for libirc from the source code.
