.TH "libirc_doc_faq.h" 3 "31 Oct 2004" "libircclient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libirc_doc_faq.h \- This file contains libircclient FAQ. 
.SH SYNOPSIS
.br
.PP
.SH "DETAILED DESCRIPTION"
.PP 
This file contains libircclient FAQ.
.PP
.PP
\fBAuthor: \fP
.in +1c
Georgy Yunaev 
.PP
\fBVersion: \fP
.in +1c
1.0 
.PP
\fBDate: \fP
.in +1c
09.2004
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for libircclient from the source code.
