/* 
 * Copyright (C) 2004 Georgy Yunaev tim@krasnogorsk.ru
 *
 * This library is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU Lesser General Public License as published by 
 * the Free Software Foundation; either version 2 of the License, or (at your 
 * option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public 
 * License for more details.
 *
 * $Id$
 */

/*! 
 * \file libirc_errors.h
 * \author Georgy Yunaev
 * \version 1.0
 * \date 09.2004
 * \brief This file defines error codes generated by libircclient.
 */

#ifndef INCLUDE_IRC_ERRORS_H
#define INCLUDE_IRC_ERRORS_H

#ifndef IN_INCLUDE_LIBIRC_H
	#error This file should not be included directly, include just libircclient.h
#endif


#define LIBIRC_ERR_OK			0
#define LIBIRC_ERR_INVAL		1
#define LIBIRC_ERR_RESOLV		2
#define LIBIRC_ERR_SOCKET		3
#define LIBIRC_ERR_CONNECT		4
#define LIBIRC_ERR_CLOSED		5
#define LIBIRC_ERR_NOMEM		6
#define LIBIRC_ERR_ACCEPT		7
#define LIBIRC_ERR_NOTFOUND		8
#define LIBIRC_ERR_NODCCSEND	9
#define LIBIRC_ERR_READ			10
#define LIBIRC_ERR_WRITE		11
#define LIBIRC_ERR_STATE		12
#define LIBIRC_ERR_TIMEOUT		13
#define LIBIRC_ERR_OPENFILE		14
#define LIBIRC_ERR_TERMINATED	15

#define LIBIRC_ERR_MAX			16

#endif /* INCLUDE_IRC_ERRORS_H */
